services:
  web:
    build:
      context: .
    volumes:
      - .:/cargo
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py loaddata
        python manage.py runserver 0.0.0.0:8000


  db:
    image: postgres:12.16-alpine

  redis:
    image: redis:7.2-alpine
    expose:
      - 6379

  worker:
    build:
      context: .
    entrypoint: celery
    volumes:
      - .:/cargo
    depends_on:
      - web
      - redis
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    command: -A cargo worker -B --loglevel=info


  flower:
    build:
      context: .
    entrypoint: celery
    volumes:
      - .:/cargo
    depends_on:
      - worker
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    command: -A cargo flower
